# Use an official Python runtime as a parent image
FROM python:3.12-slim AS base

# Set the working directory in the container
WORKDIR /usr/src/app

# Install system dependencies required for Firefox and GeckoDriver
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    firefox-esr \
    && rm -rf /var/lib/apt/lists/* \
    && GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4) \
    && wget -q "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz" -O /tmp/geckodriver.tar.gz \
    && tar -xzf /tmp/geckodriver.tar.gz -C /usr/local/bin \
    && rm /tmp/geckodriver.tar.gz \
    && chmod +x /usr/local/bin/geckodriver

# Set display port to avoid crash
ENV DISPLAY=:99

FROM base AS app

# Copy application files
COPY main.py ./
COPY requirements-test.txt ./
COPY app ./
COPY tests ./

RUN pip install --no-cache-dir -r requirements-test.txt
